services:
  - type: web
    name: tcgapplications
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUBLIC_BASE_URL
        value: https://tcgapplications.onrender.com
      - key: SCAN_TOKEN
        sync: false
      - key: ADMIN_TOKEN
        sync: false
